### ISSUE TITLE
Data needs to be stored in Australia

### ISSUE THREAD

**Issue by noobling** [noobling/Homefornow#54]
This is a Government requirement.

**Comment by alexarnold94** [comment]
I can confirm that the Firebase Storage Bucket is in Australia (had to select a region when creating the project)

**Comment by JeremiahPinto** [comment]
@noobling Have u looked further into this issue
Will be a major concern since we are launching in 4 days

**Comment by noobling** [comment]
@JeremiahPinto Yeah we can use aws im sure there are other platforms but this is highly technical area however e.g. whether we should separate database and server. What size server we need, load balancers, security groups etc. I will need to use some of our funds to learn more about it on our aws account.

**Comment by noobling** [comment]
Alright done we are using mongo atlas with a server in sydney, I have the db uri to connect to. Only issue now is its a new database we have no admin account so how would we create new service accounts? I am thinking of exporting our mlab one to mongo atlas.
