### ISSUE TITLE
This code probably will fail when there are actually dlocations i.e. unavailable services

### ISSUE THREAD

**Issue by noobling** [noobling/Homefornow#70]
`dlocationImgs[locations.indexOf(location)]`

**Comment by JeremiahPinto** [comment]
Modified all beds in Calvary house in crisis to occupied, still showed as available in the list of bed vacancies

**Comment by noobling** [comment]
@JeremiahPinto Fixed with 5c8ea39ed1479b5c26b45eb03512ca0dcd567e6b
